---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: csi-vault
  labels:
    name: csi-vault
spec:
  accessModes:
  - ReadOnlyMany
  capacity:
    storage: 100Gi
  csi:
    driver: csi-vault
    volumeHandle: data-id
    volumeAttributes: 
      server: 127.0.0.1
      share: /export
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-vault
spec:
  accessModes:
  - ReadOnlyMany
  selector:
    matchExpressions:
    - key: name
      operator: In
      values: ["csi-vault"]
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx 
spec:
  containers:
  - image: maersk/nginx
    imagePullPolicy: Always
    name: nginx
    ports:
    - containerPort: 80
      protocol: TCP
    volumeMounts:
      - mountPath: /var/run/secrets/vault
        name: csi-vault
  volumes:
  - name: csi-vault
    persistentVolumeClaim:
      claimName: csi-vault 
